-- Ejecutar este archivo en Supabase SQL Editor.
-- No contiene secretos. Requiere crear al menos un usuario en Authentication > Users.

create extension if not exists pgcrypto;

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  nombre text not null,
  codigo text,
  categoria text not null,
  precio numeric(10,2) not null default 0 check (precio >= 0),
  descripcion text,
  imagen_url text,
  destacado boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists products_categoria_idx on public.products (categoria);
create index if not exists products_destacado_idx on public.products (destacado);

alter table public.products enable row level security;

drop policy if exists "products_public_read" on public.products;
create policy "products_public_read" on public.products for select using (true);

drop policy if exists "products_authenticated_insert" on public.products;
create policy "products_authenticated_insert" on public.products for insert to authenticated with check (true);

drop policy if exists "products_authenticated_update" on public.products;
create policy "products_authenticated_update" on public.products for update to authenticated using (true) with check (true);

drop policy if exists "products_authenticated_delete" on public.products;
create policy "products_authenticated_delete" on public.products for delete to authenticated using (true);

insert into storage.buckets (id, name, public)
values ('product-images', 'product-images', true)
on conflict (id) do update set public = true;

drop policy if exists "product_images_public_read" on storage.objects;
create policy "product_images_public_read" on storage.objects for select using (bucket_id = 'product-images');

drop policy if exists "product_images_authenticated_insert" on storage.objects;
create policy "product_images_authenticated_insert" on storage.objects for insert to authenticated with check (bucket_id = 'product-images');

drop policy if exists "product_images_authenticated_update" on storage.objects;
create policy "product_images_authenticated_update" on storage.objects for update to authenticated using (bucket_id = 'product-images') with check (bucket_id = 'product-images');

drop policy if exists "product_images_authenticated_delete" on storage.objects;
create policy "product_images_authenticated_delete" on storage.objects for delete to authenticated using (bucket_id = 'product-images');
