const PRODUCT_IMAGE_BUCKET = 'product-images';
const ITEMS_PER_PAGE = 12;
let allProducts = [], filteredProducts = [], currentPage = 1;
let currentView = 'grid', currentSort = 'default', currentSearch = '', currentCategory = null;
const PLACEHOLDER = 'data:image/svg+xml,%3Csvg xmlns=%22http://www.w3.org/2000/svg%22 width=%22400%22 height=%22400%22 viewBox=%220 0 400 400%22%3E%3Crect width=%22400%22 height=%22400%22 fill=%22%230d0d0d%22/%3E%3Ctext x=%2250%25%22 y=%2250%25%22 dominant-baseline=%22middle%22 text-anchor=%22middle%22 font-family=%22sans-serif%22 font-size=%2228%22 fill=%22%23C9A84C%22%3EGin%26Jes%3C/text%3E%3C/svg%3E';
function getSupabaseClient(){return window.supabaseClient||window.supabase||null;}
function getImageUrl(value){if(!value)return PLACEHOLDER;const raw=String(value).trim();if(/^https?:\/\//i.test(raw))return raw;const client=getSupabaseClient();if(!client?.storage)return PLACEHOLDER;const clean=raw.replace(/^\/+/, '').replace(/^product-images\//i,'');const url=client.storage.from(PRODUCT_IMAGE_BUCKET).getPublicUrl(clean).data?.publicUrl;return url ? `${url}${url.includes('?')?'&':'?'}v=${encodeURIComponent(clean)}` : PLACEHOLDER;}
function handleImgError(e){if(e.target.dataset.fallback)return;e.target.dataset.fallback='1';e.target.src=PLACEHOLDER;}
function formatPrecio(precio){const n=parseFloat(precio);if(!n||n<=0)return '<span style="font-size:var(--f-sm);color:var(--text-3);font-weight:500">Consultar precio</span>';return '<span class="pcard-price">S/ '+n.toFixed(2)+'</span>';}
function formatPrecioModal(precio){const n=parseFloat(precio);return(!n||n<=0)?'Consultar precio':'S/ '+n.toFixed(2);}
function escAttr(s){return String(s??'').replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/</g,'&lt;').replace(/>/g,'&gt;');}
async function initProducts(){const loading=document.getElementById('loading-state'),grid=document.getElementById('product-grid');if(loading)loading.style.display='grid';if(grid)grid.classList.add('hidden');let data=null;try{data=await loadProductsFromSupabase();}catch(e){console.warn('Supabase:',e);}if(data?.length)data=data.map(p=>({...p,id:Number(p.id),precio:parseFloat(p.precio)||0}));allProducts=data?.length?data:[...fallbackProducts];filteredProducts=[...allProducts];if(grid)grid.addEventListener('error',handleImgError,true);if(loading)loading.style.display='none';if(grid)grid.classList.remove('hidden');buildCategoryButtons();updateCounts();applyFilters();}
function buildCategoryButtons(){const container=document.getElementById('sidebar-cats')||document.getElementById('cat-buttons');if(!container)return;const cats=[...new Set(allProducts.map(p=>p.categoria).filter(Boolean))].sort();container.innerHTML='<li><button class="cat-btn active" data-cat="all" onclick="filterProducts(null)">Todos <span id="count-all">('+allProducts.length+')</span></button></li>'+cats.map(c=>'<li><button class="cat-btn" data-cat="'+escAttr(c)+'" onclick="filterProducts(\''+escAttr(c)+'\')">'+escAttr(c)+' <span></span></button></li>').join('');}
function updateCounts(){document.querySelectorAll('.cat-btn[data-cat]').forEach(btn=>{const el=btn.querySelector('span');if(!el)return;const n=btn.dataset.cat==='all'?allProducts.length:allProducts.filter(p=>p.categoria===btn.dataset.cat).length;el.textContent='('+n+')';});}
function filterProducts(cat){currentCategory=cat;currentPage=1;currentSearch='';const si=document.getElementById('search-input');if(si)si.value='';document.querySelectorAll('.cat-btn').forEach(b=>b.classList.toggle('active',b.dataset.cat===(cat||'all')));applyFilters();document.getElementById('tienda')?.scrollIntoView({behavior:'smooth'});}
function searchProducts(q){currentSearch=String(q||'').toLowerCase();currentPage=1;applyFilters();}
function sortProducts(v){currentSort=v;applyFilters();}
function filterByPrice(){currentPage=1;applyFilters();}
function applyFilters(){let list=[...allProducts];if(currentCategory)list=list.filter(p=>p.categoria===currentCategory);if(currentSearch)list=list.filter(p=>(p.nombre||'').toLowerCase().includes(currentSearch)||(p.codigo||'').toLowerCase().includes(currentSearch)||(p.descripcion||'').toLowerCase().includes(currentSearch));const mn=parseFloat(document.getElementById('price-min')?.value)||0,mx=parseFloat(document.getElementById('price-max')?.value)||Infinity;list=list.filter(p=>(p.precio||0)>=mn&&(p.precio||0)<=mx);if(currentSort==='price-asc')list.sort((a,b)=>(a.precio||0)-(b.precio||0));if(currentSort==='price-desc')list.sort((a,b)=>(b.precio||0)-(a.precio||0));if(currentSort==='name-asc')list.sort((a,b)=>String(a.nombre).localeCompare(String(b.nombre)));filteredProducts=list;renderPage();}
function renderPage(){const s=(currentPage-1)*ITEMS_PER_PAGE,items=filteredProducts.slice(s,s+ITEMS_PER_PAGE),total=filteredProducts.length,el=document.getElementById('results-count');if(el)el.textContent='Mostrando '+(total?Math.min(s+1,total):0)+'–'+Math.min(s+ITEMS_PER_PAGE,total)+' de '+total+' producto'+(total!==1?'s':'');renderCards(items);renderPagination(total);}
function setView(v){currentView=v;document.getElementById('product-grid')?.classList.toggle('list-view',v==='list');document.getElementById('btn-grid')?.classList.toggle('active',v==='grid');document.getElementById('btn-list')?.classList.toggle('active',v==='list');renderPage();}
function renderCards(list){const grid=document.getElementById('product-grid');if(!grid)return;if(!list.length){grid.innerHTML='<div style="grid-column:1/-1;text-align:center;padding:4rem 0;color:var(--text-3);font-size:.85rem;letter-spacing:.1em">No se encontraron productos. <button onclick="filterProducts(null)" style="color:var(--gold);text-decoration:underline;cursor:pointer;">Ver todos</button></div>';return;}grid.innerHTML=list.map((p,i)=>{const img=getImageUrl(p.imagen_url),badge=p.destacado?'<div class="pcard-badge">Destacado</div>':'',nom=escAttr(p.nombre);return currentView==='list'?`<div class="pcard list" style="animation-delay:${i*.04}s" onclick="openModal(${p.id})"><div class="pcard-img"><img src="${img}" alt="${nom}" loading="lazy" width="100" height="100" onerror="handleImgError(event)"></div><div class="pcard-body"><p class="pcard-cat">${escAttr(p.categoria)}</p><p class="pcard-code">${escAttr(p.codigo||'')}</p><h4 class="pcard-name">${nom}</h4><div class="pcard-foot">${formatPrecio(p.precio)}<button class="pcard-add" onclick="event.stopPropagation();addToCart(${p.id})">+ Agregar</button></div></div></div>`:`<div class="pcard" style="animation-delay:${i*.04}s" onclick="openModal(${p.id})">${badge}<div class="pcard-img"><img src="${img}" alt="${nom}" loading="lazy" width="400" height="400" onerror="handleImgError(event)"></div><div class="pcard-body"><p class="pcard-cat">${escAttr(p.categoria)}</p><p class="pcard-code">${escAttr(p.codigo||'')}</p><h4 class="pcard-name">${nom}</h4><div class="pcard-foot">${formatPrecio(p.precio)}<button class="pcard-add" onclick="event.stopPropagation();addToCart(${p.id})">+ Agregar</button></div></div></div>`;}).join('');}
function renderPagination(total){const pages=Math.ceil(total/ITEMS_PER_PAGE),pag=document.getElementById('pagination');if(!pag)return;if(pages<=1){pag.classList.add('hidden');return;}pag.classList.remove('hidden');pag.innerHTML=Array.from({length:pages},(_,i)=>i+1).map(p=>'<button class="page-btn'+(p===currentPage?' active':'')+'" onclick="goToPage('+p+')">'+p+'</button>').join('');}
function goToPage(p){currentPage=p;renderPage();document.getElementById('tienda')?.scrollIntoView({behavior:'smooth'});}
function openModal(id){const p=allProducts.find(x=>Number(x.id)===Number(id));if(!p)return;const modalImg=document.getElementById('modal-img');if(modalImg){modalImg.src=getImageUrl(p.imagen_url);modalImg.alt=p.nombre;modalImg.onerror=()=>handleImgError({target:modalImg});}document.getElementById('modal-cat').textContent=p.categoria||'';document.getElementById('modal-name').textContent=p.nombre||'';document.getElementById('modal-code').textContent=p.codigo?'Cód. '+p.codigo:'';document.getElementById('modal-desc').textContent=p.descripcion||'';document.getElementById('modal-price').textContent=formatPrecioModal(p.precio);document.getElementById('modal-btn').onclick=()=>{addToCart(p.id);closeModal();};document.getElementById('modal-wa').href='https://wa.me/51926894528?text=Hola%20Hebillas%20Gin%26Jes%2C%20me%20interesa%3A%20'+encodeURIComponent(p.nombre)+'%20('+encodeURIComponent(p.codigo||'')+')';document.getElementById('product-modal').classList.add('open');document.body.style.overflow='hidden';}
function closeModal(){document.getElementById('product-modal')?.classList.remove('open');document.body.style.overflow='';}
document.addEventListener('DOMContentLoaded',initProducts);
