const {test, before, after} = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const {PGlite} = require('@electric-sql/pglite');
const migration = fs.readFileSync('supabase/migrations/202609300001_catalog.sql','utf8');
const admin = '11111111-1111-1111-1111-111111111111';
const other = '22222222-2222-2222-2222-222222222222';
let db;
const bootstrap = `
create role anon; create role authenticated;
create schema auth; create schema storage;
create table auth.users(id uuid primary key);
create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
grant usage on schema auth, public, storage to anon, authenticated;
grant execute on function auth.uid() to anon, authenticated;
create table storage.buckets(id text primary key, name text, public boolean);
create table storage.objects(id bigint generated by default as identity primary key, bucket_id text, name text);
alter table storage.objects enable row level security;
grant select, insert, update, delete on storage.objects to anon, authenticated;
grant usage on sequence storage.objects_id_seq to anon, authenticated;
create policy legacy_open_storage on storage.objects for all to anon, authenticated using (true) with check (true);
`;
const legacy = `create table public.products (
id bigint generated by default as identity primary key, nombre text not null, codigo text, categoria text not null,
precio numeric(10,2) not null default 0 check(precio >= 0), descripcion text, imagen_url text,
destacado boolean not null default false, activo boolean default true,
created_at timestamptz not null default now(), updated_at timestamptz not null default now());
alter table public.products enable row level security;
create policy products_authenticated_update on public.products for all to authenticated using (true) with check (true);
insert into public.products(nombre,codigo,categoria,imagen_url,activo) values
('Uno','abc',' Metales ','folder/one.jpg',true), ('Dos',' ABC ','Metales','https://old.test/dos.jpg',false),
('Tres',null,'Plásticos',null,true), ('Cuatro','LEGACY-3','Plásticos',null,true), ('Cinco','inválido','Broches',null,true);`;
async function role(name, uid = '') { await db.exec(`reset role; set request.jwt.claim.sub = '${uid}'; set role ${name};`); }
async function scalar(sql) { return Object.values((await db.query(sql)).rows[0])[0]; }
function row(i, extra = {}) { return {codigo:`CSV-${i}`, nombre:`Producto ${i}`, categoria:'Metales',subcategoria:'Broches',precio:1.5,descripcion:'Descripción',imagen_url:'metales/img.jpg',activo:true,destacado:false,...extra}; }
async function importRows(rows, mode = 'insert') { return db.query('select public.import_catalog($1::jsonb,$2::text) as imported',[JSON.stringify(rows),mode]); }
before(async () => {
  db = new PGlite(); await db.exec(bootstrap + legacy); await db.exec(migration);
  await db.exec(`insert into auth.users values ('${admin}'),('${other}'); insert into public.catalog_admins values ('${admin}');`);
});
after(async () => { await db.close(); });
test('migration retains all IDs, images, inactive state, taxonomy and original codes', async () => {
  assert.equal(await scalar('select count(*) from public.products'),5);
  const rows = (await db.query('select * from public.products order by id')).rows;
  assert.deepEqual(rows.map(p => p.id),[1,2,3,4,5]);
  assert.deepEqual(rows.map(p => p.codigo),['ABC','LEGACY-2','LEGACY-3-1','LEGACY-3','LEGACY-5']);
  assert.equal(rows[1].activo,false); assert.equal(rows[1].imagen_url,'https://old.test/dos.jpg');
  assert.equal(await scalar('select count(*) from public.categories'),3);
  assert.equal(await scalar('select original_codigo from public.catalog_migration_audit where product_id=2'),' ABC ');
});
test('migration and schema are repeatable without losing products', async () => {
  await db.exec(migration);
  assert.equal(await scalar('select count(*) from public.products'),5);
  const schema = fs.readFileSync('supabase/schema.sql','utf8'); assert(schema.replace(/\r/g,'').endsWith(migration.replace(/\r/g,'')));
});
test('anonymous users read active only and cannot write products or storage', async () => {
  await role('anon');
  assert.equal(await scalar('select count(*) from public.products'),4);
  await assert.rejects(db.exec("insert into public.products(nombre,codigo,categoria) values('Hack','HACK','Metales')"));
  await assert.rejects(db.exec("insert into storage.objects(bucket_id,name) values('product-images','hack.jpg')"));
  await assert.rejects(importRows([row(0)]));
  await role('postgres');
});
test('ordinary authenticated users cannot promote themselves or write catalog/images', async () => {
  await role('authenticated',other);
  assert.equal(await scalar('select public.is_catalog_admin()'),false);
  assert.equal(await scalar('select count(*) from public.products'),4);
  assert.equal((await db.query("update public.products set nombre='Hack' returning id")).rows.length,0);
  assert.equal((await db.query('delete from public.products returning id')).rows.length,0);
  await assert.rejects(db.exec(`insert into public.catalog_admins values('${other}')`));
  await assert.rejects(db.exec("insert into public.categories(nombre) values('Hack')"));
  await assert.rejects(db.exec("insert into storage.objects(bucket_id,name) values('product-images','hack.jpg')"));
  await assert.rejects(importRows([row(0)]),/administrador/);
  await role('postgres');
});
test('admin imports 250 products atomically, preserving legacy rows', async () => {
  await role('authenticated',admin);
  assert.equal(await scalar('select count(*) from public.products'),5);
  const result = await importRows(Array.from({length:250},(_,i) => row(i)));
  assert.equal(result.rows[0].imported,250);
  assert.equal(await scalar('select count(*) from public.products'),255);
  assert.equal(await scalar("select count(*) from public.subcategories where nombre='Broches'"),1);
  await db.exec("insert into storage.objects(bucket_id,name) values('product-images','ok.jpg')");
  await role('postgres');
});
test('invalid row and duplicate existing code rollback products AND new taxonomy', async () => {
  await role('authenticated',admin);
  await assert.rejects(importRows([row(300,{categoria:'Temporal'}),row(301,{precio:-1})]),/Registro 3/);
  assert.equal(await scalar("select count(*) from public.categories where nombre='Temporal'"),0);
  await assert.rejects(importRows([row(300),row(0)]),/duplicate key/);
  assert.equal(await scalar("select count(*) from public.products where codigo='CSV-300'"),0);
  await assert.rejects(importRows([row(300),row(300,{codigo:'csv-300'})]),/repetidos/);
  await assert.rejects(importRows([row(300,{activo:'true'})]),/booleanos/);
  await role('postgres');
});
test('upsert preserves ID and explicitly replaces fields; bulk updates enforce category relationship', async () => {
  await role('authenticated',admin);
  const id = await scalar("select id from public.products where codigo='CSV-0'");
  await importRows([row(0,{nombre:'Actualizado',categoria:'Plásticos',subcategoria:'',imagen_url:'',activo:false})],'upsert');
  const product = (await db.query("select * from public.products where codigo='CSV-0'")).rows[0];
  assert.equal(product.id,id); assert.equal(product.imagen_url,''); assert.equal(product.activo,false); assert.equal(product.categoria,'Plásticos'); assert.equal(product.subcategory_id,null);
  await assert.rejects(db.exec("update public.products set subcategory_id=(select id from public.subcategories limit 1) where codigo='CSV-0'"),/foreign key/);
  const changed = await db.query("update public.products set activo=false where codigo in ('CSV-1','CSV-2') returning id"); assert.equal(changed.rows.length,2);
  await assert.rejects(db.exec("insert into public.products(nombre,codigo,categoria) values('Duplicado',' abc ','Metales')"),/duplicate key/);
  await role('postgres');
});
test('storage guards block update/delete under unknown permissive legacy policies', async () => {
  await role('authenticated',other);
  assert.equal((await db.query("update storage.objects set name='hack' where bucket_id='product-images' returning id")).rows.length,0);
  assert.equal((await db.query("delete from storage.objects where bucket_id='product-images' returning id")).rows.length,0);
  await role('postgres');
});
test('seed is additive and repeatable', async () => {
  const before = await scalar('select count(*) from public.products');
  await db.exec(fs.readFileSync('supabase/seed.sql','utf8'));
  assert.equal(await scalar('select count(*) from public.products'),before + 17);
  await db.exec(fs.readFileSync('supabase/seed.sql','utf8'));
  assert.equal(await scalar('select count(*) from public.products'),before + 17);
});
test('fresh installation and legacy productos rename succeed; ambiguous dual tables rollback', async () => {
  for (const scenario of ['fresh','rename','both']) {
    const instance = new PGlite(); await instance.exec(bootstrap);
    if (scenario !== 'fresh') await instance.exec(legacy + 'alter table public.products rename to productos;');
    if (scenario === 'rename') await instance.exec("update public.productos set id=100 where id=5;");
    if (scenario === 'both') await instance.exec('create table public.products(id bigint);');
    if (scenario === 'both') {
      await assert.rejects(instance.exec(migration), /Existen products y productos/);
      await instance.exec('rollback');
      assert.equal((await instance.query('select count(*) as n from public.productos')).rows[0].n,5);
    } else {
      await instance.exec(migration);
      assert.equal((await instance.query('select count(*) as n from public.products')).rows[0].n,scenario === 'fresh' ? 0 : 5);
      if (scenario === 'rename') assert.equal((await instance.query("insert into public.products(nombre,codigo,categoria) values('Nuevo','NEW','Metales') returning id")).rows[0].id,101);
    }
    await instance.close();
  }
});
