-- Ejecutar completo en SQL Editor como postgres. No ejecuta seed ni borra productos.
begin;

do $$
begin
  if to_regclass('public.productos') is not null then
    if to_regclass('public.products') is not null then
      raise exception 'Existen products y productos. Reconciliar ambas tablas antes de migrar; no se ha cambiado nada.';
    end if;
    alter table public.productos rename to products;
  end if;
end $$;

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  nombre text not null, codigo text, categoria text not null,
  precio numeric(10,2) not null default 0 check (precio >= 0),
  descripcion text, imagen_url text, destacado boolean not null default false,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
lock table public.products in access exclusive mode;
alter table public.products add column if not exists activo boolean not null default true;
alter table public.products add column if not exists updated_at timestamptz not null default now();
update public.products set activo = true where activo is null;
alter table public.products alter column activo set default true;
alter table public.products alter column activo set not null;

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  nombre text not null check (length(btrim(nombre)) between 1 and 100)
);
create unique index if not exists categories_name_unique on public.categories (lower(btrim(nombre)));
create table if not exists public.subcategories (
  id bigint generated by default as identity primary key,
  category_id bigint not null references public.categories(id) on delete restrict,
  nombre text not null check (length(btrim(nombre)) between 1 and 100),
  unique (id, category_id)
);
create unique index if not exists subcategories_name_unique on public.subcategories (category_id, lower(btrim(nombre)));
alter table public.products add column if not exists category_id bigint references public.categories(id) on delete restrict;
alter table public.products add column if not exists subcategory_id bigint;
do $$ begin
  if not exists (select 1 from pg_constraint where conrelid = 'public.products'::regclass and conname = 'products_subcategory_category_fk') then
    alter table public.products add constraint products_subcategory_category_fk foreign key (subcategory_id, category_id) references public.subcategories(id, category_id) on delete restrict;
  end if;
end $$;

-- Retener una copia de los valores originales; solo SQL Editor puede consultarla.
create table if not exists public.catalog_migration_audit (
  product_id bigint primary key, original_codigo text, original_categoria text,
  migrated_at timestamptz not null default now()
);
insert into public.catalog_migration_audit(product_id, original_codigo, original_categoria)
select id, codigo, categoria from public.products on conflict do nothing;
alter table public.catalog_migration_audit enable row level security;
revoke all on public.catalog_migration_audit from public, anon, authenticated;

insert into public.categories(nombre)
select distinct coalesce(nullif(btrim(categoria), ''), 'Sin categoría') from public.products
on conflict do nothing;
update public.products p set category_id = c.id
from public.categories c where p.category_id is null and lower(btrim(c.nombre)) = lower(coalesce(nullif(btrim(p.categoria), ''), 'Sin categoría'));
update public.products p set categoria = c.nombre from public.categories c where p.category_id = c.id;
alter table public.products alter column category_id set not null;

-- Normalizar códigos; conservar el primer duplicado y asignar LEGACY-id al resto.
-- Evitar colisiones incluso si ya existe un código LEGACY-id.
do $$ declare r record; candidate text; suffix integer;
begin
  for r in select id, codigo from public.products order by id loop
    candidate := upper(btrim(coalesce(r.codigo, '')));
    if candidate !~ '^[A-Z0-9][A-Z0-9._/-]{0,63}$' or exists (
      select 1 from public.products where id < r.id and upper(btrim(codigo)) = candidate
    ) then
      candidate := 'LEGACY-' || r.id; suffix := 0;
      while exists (select 1 from public.products where id <> r.id and upper(btrim(codigo)) = candidate) loop
        suffix := suffix + 1; candidate := 'LEGACY-' || r.id || '-' || suffix;
      end loop;
    end if;
    update public.products set codigo = candidate where id = r.id and codigo is distinct from candidate;
  end loop;
end $$;
alter table public.products alter column codigo set not null;
create unique index if not exists products_codigo_unique on public.products(codigo);
do $$ begin
  if not exists (select 1 from pg_constraint where conrelid = 'public.products'::regclass and conname = 'products_codigo_format') then
    alter table public.products add constraint products_codigo_format check (codigo ~ '^[A-Z0-9][A-Z0-9._/-]{0,63}$');
  end if;
end $$;
create index if not exists products_category_page_idx on public.products(category_id, activo, id);
create index if not exists products_subcategory_page_idx on public.products(subcategory_id, activo, id);
create index if not exists products_active_featured_idx on public.products(activo, destacado desc, id);

-- No se concede el rol automáticamente a todos los usuarios existentes.
create table if not exists public.catalog_admins (
  user_id uuid primary key references auth.users(id) on delete cascade
);
alter table public.catalog_admins enable row level security;
revoke all on public.catalog_admins from public, anon, authenticated;
create or replace function public.is_catalog_admin() returns boolean
language sql stable security definer set search_path = '' as $$
  select exists (select 1 from public.catalog_admins where user_id = (select auth.uid()));
$$;
revoke all on function public.is_catalog_admin() from public;
grant execute on function public.is_catalog_admin() to anon, authenticated;

-- Trigger de compatibilidad para el campo categoria antiguo y códigos canónicos.
create or replace function public.sync_catalog_product() returns trigger
language plpgsql security invoker set search_path = '' as $$
declare resolved bigint;
begin
  new.codigo := upper(btrim(new.codigo));
  if new.category_id is null or (tg_op = 'UPDATE' and new.categoria is distinct from old.categoria and new.category_id is not distinct from old.category_id) then
    if nullif(btrim(new.categoria), '') is null then raise exception 'Categoría obligatoria'; end if;
    insert into public.categories(nombre) values (btrim(new.categoria)) on conflict do nothing;
    select id into resolved from public.categories where lower(btrim(nombre)) = lower(btrim(new.categoria));
    new.category_id := resolved;
  end if;
  select nombre into new.categoria from public.categories where id = new.category_id;
  if new.categoria is null then raise exception 'Categoría no encontrada'; end if;
  new.updated_at := now();
  return new;
end $$;
revoke all on function public.sync_catalog_product() from public, anon, authenticated;
drop trigger if exists sync_catalog_product on public.products;
create trigger sync_catalog_product before insert or update on public.products for each row execute function public.sync_catalog_product();

-- Reemplazar las políticas anteriores (permisivas) de estas tablas de catálogo.
do $$ declare r record; t text;
begin
  for r in select schemaname, tablename, policyname from pg_policies where schemaname = 'public' and tablename in ('products','categories','subcategories') loop
    execute format('drop policy %I on %I.%I', r.policyname, r.schemaname, r.tablename);
  end loop;
  foreach t in array array['products','categories','subcategories'] loop
    execute format('alter table public.%I enable row level security', t);
    execute format('revoke all on public.%I from public, anon, authenticated', t);
    execute format('grant select on public.%I to anon, authenticated', t);
    execute format('grant insert, update, delete on public.%I to authenticated', t);
    execute format('create policy catalog_admin_write on public.%I for all to authenticated using ((select public.is_catalog_admin())) with check ((select public.is_catalog_admin()))', t);
  end loop;
end $$;
create policy catalog_public_read on public.products for select to anon, authenticated using (activo);
create policy catalog_public_read on public.categories for select to anon, authenticated using (true);
create policy catalog_public_read on public.subcategories for select to anon, authenticated using (true);
-- Secuencias exactas (también cubre una tabla productos renombrada).
do $$ declare t text; seq text; maximum_id bigint; sequence_value bigint;
begin
  foreach t in array array['products','categories','subcategories'] loop
    seq := pg_get_serial_sequence('public.' || t, 'id');
    if seq is not null then
      execute format('grant usage on sequence %s to authenticated', seq);
      -- Las cargas históricas con IDs explícitos pueden haber dejado la secuencia atrás.
      execute format('select max(id) from public.%I', t) into maximum_id;
      execute format('select last_value from %s', seq) into sequence_value;
      if maximum_id >= sequence_value then perform setval(seq::regclass, maximum_id, true); end if;
    end if;
  end loop;
end $$;

insert into storage.buckets(id, name, public) values ('product-images', 'product-images', true)
on conflict (id) do nothing;
drop policy if exists product_images_public_read on storage.objects;
create policy product_images_public_read on storage.objects for select to anon, authenticated using (bucket_id = 'product-images');
drop policy if exists product_images_authenticated_insert on storage.objects;
drop policy if exists product_images_authenticated_update on storage.objects;
drop policy if exists product_images_authenticated_delete on storage.objects;
drop policy if exists product_images_admin on storage.objects;
create policy product_images_admin on storage.objects for all to authenticated using (bucket_id = 'product-images' and (select public.is_catalog_admin())) with check (bucket_id = 'product-images' and (select public.is_catalog_admin()));
-- Guardas restrictivas: una política permisiva antigua desconocida no permite escribir aquí.
drop policy if exists product_images_insert_guard on storage.objects;
create policy product_images_insert_guard on storage.objects as restrictive for insert to public with check (bucket_id <> 'product-images' or (select public.is_catalog_admin()));
drop policy if exists product_images_update_guard on storage.objects;
create policy product_images_update_guard on storage.objects as restrictive for update to public using (bucket_id <> 'product-images' or (select public.is_catalog_admin())) with check (bucket_id <> 'product-images' or (select public.is_catalog_admin()));
drop policy if exists product_images_delete_guard on storage.objects;
create policy product_images_delete_guard on storage.objects as restrictive for delete to public using (bucket_id <> 'product-images' or (select public.is_catalog_admin()));

-- Un solo RPC = una transacción. Cualquier error revierte productos y taxonomía.
create or replace function public.import_catalog(rows jsonb, mode text default 'insert') returns integer
language plpgsql security invoker set search_path = '' as $$
declare item jsonb; n integer := 0; cat bigint; sub bigint; code text; price numeric; result integer;
begin
  if not public.is_catalog_admin() then raise exception 'Se requiere un administrador del catálogo' using errcode = '42501'; end if;
  if mode is null or mode not in ('insert','upsert') then raise exception 'Modo inválido'; end if;
  if rows is null or jsonb_typeof(rows) <> 'array' then raise exception 'Se esperaba una lista'; end if;
  if jsonb_array_length(rows) not between 1 and 1000 then raise exception 'Se permiten 1 a 1000 productos'; end if;
  if exists (select 1 from jsonb_array_elements(rows) e group by upper(btrim(e->>'codigo')) having count(*) > 1) then raise exception 'Códigos repetidos en el archivo'; end if;
  for item in select value from jsonb_array_elements(rows) loop
    n := n + 1;
    begin
      code := upper(btrim(item->>'codigo'));
      if code is null or code !~ '^[A-Z0-9][A-Z0-9._/-]{0,63}$' then raise exception 'Código inválido'; end if;
      if coalesce(length(btrim(item->>'nombre')),0) not between 1 and 200 then raise exception 'Nombre inválido'; end if;
      if coalesce(length(btrim(item->>'categoria')),0) not between 1 and 100 or coalesce(length(btrim(item->>'subcategoria')),0) > 100 then raise exception 'Categoría/subcategoría inválida'; end if;
      if coalesce(item->>'precio','') !~ '^[0-9]+(\.[0-9]{1,2})?$' then raise exception 'Precio inválido'; end if;
      price := (item->>'precio')::numeric;
      if price > 99999999.99 then raise exception 'Precio fuera de rango'; end if;
      if jsonb_typeof(item->'activo') is distinct from 'boolean' or jsonb_typeof(item->'destacado') is distinct from 'boolean' then raise exception 'activo y destacado deben ser booleanos'; end if;
      if coalesce(length(item->>'descripcion'),0) > 5000 or coalesce(length(item->>'imagen_url'),0) > 2048 then raise exception 'Texto demasiado largo'; end if;
      if (item->>'imagen_url' ~* '^[a-z][a-z0-9+.-]*:' and item->>'imagen_url' !~* '^https?://') or item->>'imagen_url' like '//%' then raise exception 'URL de imagen inválida'; end if;
      insert into public.categories(nombre) values (btrim(item->>'categoria')) on conflict do nothing;
      select id into cat from public.categories where lower(btrim(nombre)) = lower(btrim(item->>'categoria'));
      sub := null;
      if nullif(btrim(item->>'subcategoria'), '') is not null then
        insert into public.subcategories(category_id,nombre) values (cat,btrim(item->>'subcategoria')) on conflict do nothing;
        select id into sub from public.subcategories where category_id = cat and lower(btrim(nombre)) = lower(btrim(item->>'subcategoria'));
      end if;
      if mode = 'upsert' then
        insert into public.products(codigo,nombre,category_id,subcategory_id,precio,descripcion,imagen_url,activo,destacado)
        values(code,btrim(item->>'nombre'),cat,sub,price,item->>'descripcion',item->>'imagen_url',(item->>'activo')::boolean,(item->>'destacado')::boolean)
        on conflict (codigo) do update set nombre=excluded.nombre, category_id=excluded.category_id, subcategory_id=excluded.subcategory_id, categoria=excluded.categoria, precio=excluded.precio, descripcion=excluded.descripcion, imagen_url=excluded.imagen_url, activo=excluded.activo, destacado=excluded.destacado;
      else
        insert into public.products(codigo,nombre,category_id,subcategory_id,precio,descripcion,imagen_url,activo,destacado)
        values(code,btrim(item->>'nombre'),cat,sub,price,item->>'descripcion',item->>'imagen_url',(item->>'activo')::boolean,(item->>'destacado')::boolean);
      end if;
    exception when others then raise exception 'Registro % (código %): %', n + 1, coalesce(code,'?'), sqlerrm; end;
  end loop;
  result := n; return result;
end $$;
revoke all on function public.import_catalog(jsonb,text) from public, anon;
grant execute on function public.import_catalog(jsonb,text) to authenticated;
notify pgrst, 'reload schema';
commit;
